### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by pawopawo** [ashaw596/squeezenas#5]
Thanks for your excellent work

hope to get the training code, which can reproduce the results of the paper

**Comment by pawopawo** [comment]
Begging for your help, thanks

**Comment by ashaw596** [comment]
Hi. Sorry due to work circumstances, I'm not sure if I will be able to publicly release the code soon. I have release some helper utilities here https://github.com/ashaw596/supernet-nas and can definitely help you use or reimplement the paper. Feel free to email me at ashaw596@gmail.com as the deepscale email on the paper unforunately no longer works.

**Comment by pawopawo** [comment]
thanks
